export const questions = [
    {
        "type": "idselect",
        "limit": 3,
        "question": "Favorite Identity (Gameplay)",
        "subquestion": "Choose up to 3",
        "options": [
            "10214", "11114", "10314", "10814", "11015", 
            "11214", "10115", "10414", "10514", "11215", 
            "10215", "10614", "10515", "10915", "10715", 
            "10415", "11115", "10615", "10815", "10716", 
            "10916", "10216", "11216"
        ]
    },
    {
        "type": "idselect",
        "limit": 3,
        "question": "Favorite Identity (Non-gameplay)",
        "subquestion": "Audio/Visual Design, Lore, Uptie Story. Choose up to 3",
        "options": [
            "10214", "11114", "10314", "10814", "11015", 
            "11214", "10115", "10414", "10514", "11215", 
            "10215", "10614", "10515", "10915", "10715", 
            "10415", "11115", "10615", "10815", "10716", 
            "10916", "10216", "11216"
        ]
    },
    {
        "type": "egoselect",
        "limit": 1,
        "question": "Favorite E.G.O",
        "options": ["20709", "21109", "20108", "20409", "21009", "20210", "20909", "20509", "20109"]
    },
    {
        "type": "select",
        "limit": 1,
        "question": "Favorite Faction/Archetype Update",
        "options": [
            "Burn",
            "Bleed",
            "Tremor",
            "Sinking",
            "Poise",
            "Charge",
            "Ammo",
            "Index",
            "Middle",
            "Ring",
            "Thumb",
            "House of Spiders",
            "LCE / E.G.O Users",
            "Blade Lineage",
            "Burn-Bleed",
            "Tremor-Sinking",
            "Bleed-Poise",
            "Rupture-Charge",
            "Dawn Office",
            "Burn-Tremor / Scorch"
        ]
    },
    {
        "type": "select",
        "limit": 3,
        "question": "Favorite Boss Fight",
        "subquestion": "Choose up to 3",
        "options": [
            "Textbook (9-3, Lucio & Automanikins)",
            "Charm (9-8, Faelantern)",
            "Wayward (9-9, Wayward Passenger)",
            "Doubt (9-10, Ebony Queen's Apple)",
            "Cigarettes & the Nursefather (9-18, Albina & Ren)",
            "Shock Centipede (9-25, Shock Centipede)",
            "The Contract 2 (9-28, Ardor Blossom Moth)",
            "Will of the Prescript (9-30, Sora)",
            "That Single Thread (9-33, Shiomi Yoru 1)",
            "The Ring (9-37, Callisto & Albina)",
            "The Middle (9-38, Matthias & Kira)",
            "Araya (9-41, Shiomi Yoru 2)",
            "Ticket (9-42, Valencina & Lucio)",
            "Hatching (9-43, Callisto & Albina 2)",
            "Family (9-44, Matthias & Kira 2)",
            "Suddenly, One Day (9-45, The Roach Emperor)",
            "Temporal Entanglement (9-48, The Pinky Nursefather)",
            "Non-self (9-49, Sora & Ren)",
            "The Spider's Thread (9-50, Rien)",
            "S.A.N.G.R.I.A. (9.5-12, Rufo)",
            "Pursuit 2 (9.5-24, Im Gyeong-eop 1)",
            "???'s Fathoms (9.5-25, Im Gyeong-eop 2)"
        ]
    },
    {
        "type": "select",
        "limit": 3,
        "question": "Favorite Non-Bus NPC",
        "subquestion": "Choose up to 3",
        "options": [
            "Saude",
            "Alyssa",
            "Marton",
            "Hohenheim",
            "Ezra",
            "Moses",
            "Aeng-du",
            "Vespa",
            "Lucio",
            "Valencina",
            "Rien",
            "Sora",
            "Matthias",
            "Kira",
            "Callisto",
            "Albina",
            "Dihui Star",
            "Ren",
            "Araya",
            "Jamila",
            "Ravi",
            "Lei Heng",
            "A Certain Sinclair",
            "Alan",
            "Émile Benoît",
            "Rufo",
            "Ted",
            "Bamboo-Hatted Kim",
            "Im Gyeong-eop",
            "Bakery Owner",
            "Flash Phenomenon"
        ]
    },
    {
        "type": "select",
        "limit": 1,
        "question": "Favorite Event",
        "options": [
            "The 8th Walpurgis Night - The Dusk of Amber",
            "LCB Regular Check-up BokGak",
            "Twining Threads",
            "Nocturnal Sweeping BokGak",
            "Refraction Railway 6 - Maru no Uchi no Sanzu no Kawa",
            "Mnestic Experience",
            "The 9th Walpurgis Night - The Fixer at Dawnbreak"
        ]
    },
    {
        "type": "themeselect",
        "limit": 3,
        "question": "Favorite Story Theme",
        "subquestion": "Selecting a theme will show its video if you're unsure which it is. Choose up to 3",
        "options": [
            { "name": "Aka No Ito", "youtubeVideoId": "R7DHmr6lKfc" },
            { "name": "Kumo No Ito", "youtubeVideoId": "MN8elM9vQMY" },
            { "name": "And Day Passes", "youtubeVideoId": "pc46smttbH4" },
            { "name": "Good Old Day", "youtubeVideoId": "1Q7csWy2krE" },
            { "name": "Sanzunokawa", "youtubeVideoId": "ZK7yzcQiXKA" },
            { "name": "They Must Be Here", "youtubeVideoId": "Z_Fs7-XiybA" },
            { "name": "Thumbs Down", "youtubeVideoId": "Sfj2ji6bv5E" },
            { "name": "They Were Here", "youtubeVideoId": "NsyxJRelU3A" },
            { "name": "Alert Alpha", "youtubeVideoId": "piA79uklc6A" },
            { "name": "Alert Beta", "youtubeVideoId": "3BDhNe_c9jI" },
            { "name": "Call New Index", "youtubeVideoId": "CbUlPeCDBSs" },
            { "name": "Cut Your Rings", "youtubeVideoId": "cAodjNjtYQs" },
            { "name": "Middle Finger Sanjou", "youtubeVideoId": "SxrfrKXrK3k" },
            { "name": "Yumenomaichiru", "youtubeVideoId": "IAEMa4pdtVo" },
            { "name": "Pass On", "youtubeVideoId": "_ABclobULoc" },
            { "name": "Fallen Rings", "youtubeVideoId": "GvGZ4-MKzhg" },
            { "name": "Middle Finger Taijou", "youtubeVideoId": "zU8t7MJCR2o" },
            { "name": "Recall", "youtubeVideoId": "7HHJFKtFiSE" },
            { "name": "Sainokawara", "youtubeVideoId": "T9R5nIw2apE" },
            { "name": "Savagery", "youtubeVideoId": "8FgSPP0HhW0" },
            { "name": "Shattered Dream", "youtubeVideoId": "6JFPala0e8k" },
            { "name": "Ordinary Walkway", "youtubeVideoId": "1FCKV91m-0g" },
            { "name": "Mise-en-scène", "youtubeVideoId": "szN0WJrpKnE" },
            { "name": "Mist on Waves", "youtubeVideoId": "CzidAseYD9I" },
            { "name": "River and Lake", "youtubeVideoId": "XX9BJDosEM8" },
            { "name": "Vengeance", "youtubeVideoId": "DszMMtvc-NA" },
        ]
    },
    {
        "type": "themeselect",
        "limit": 3,
        "question": "Favorite Battle/Boss Theme",
        "subquestion": "Selecting a theme will show its video if you're unsure which it is. Choose up to 3",
        "options": [
            { "name": "Battle Theme A", "youtubeVideoId": "S1GcTih7NQM" },
            { "name": "Battle Theme B", "youtubeVideoId": "IDFireGiqrE" },
            { "name": "Boss 1 Battle Theme 1", "youtubeVideoId": "ROtvH_365qA" },
            { "name": "Boss 1 Battle Theme 2", "youtubeVideoId": "W-BobfNM1tg" },
            { "name": "Boss 2 Battle Theme", "youtubeVideoId": "-jk4gqDFRBQ" },
            { "name": "Boss 3 Battle Theme 1", "youtubeVideoId": "XN-Wmy9B5f8" },
            { "name": "Boss 3 Battle Theme 2", "youtubeVideoId": "BuzAgy_88HM" },
            { "name": "Boss 4 Battle Theme 1", "youtubeVideoId": "JPfBZsjiPrE" },
            { "name": "Boss 4 Battle Theme 2", "youtubeVideoId": "CCU43wbwq5g" },
            { "name": "Boss 5 Battle Theme", "youtubeVideoId": "oyz_gYE4hOU" },
            { "name": "Boss 6 Battle Theme", "youtubeVideoId": "e42u_cIreaQ" },
            { "name": "Boss 7 Battle Theme", "youtubeVideoId": "7u74j6KOa3c" },
            { "name": "Boss 8 Battle Theme", "youtubeVideoId": "hPk3uU3vd9o" },
            { "name": "Boss 9 Battle Theme", "youtubeVideoId": "xzF14a_YQvY" },
            { "name": "Boss 10 Battle Theme", "youtubeVideoId": "b8fKDXWH-kI" },
            { "name": "SAIKAI", "youtubeVideoId": "h0djuhl97Kw" },
            { "name": "Intervallo VII-1 Battle Theme", "youtubeVideoId": "K2PdNLF6dTU" },
            { "name": "Intervallo VII-1 Boss Battle Theme", "youtubeVideoId": "MQdRfMkWlwI" },
            { "name": "Tandem Sentitis & Tandem Lugetis", "youtubeVideoId": "tML5A2i2kPQ" },
            { "name": "Intervallo VII-2 Battle Theme 1", "youtubeVideoId": "FWWrT-sP0SA" },
            { "name": "Intervallo VII-2 Battle Theme 2", "youtubeVideoId": "HqwAGT1iPxI" },
            { "name": "Intervallo VII-2 Boss Battle Theme", "youtubeVideoId": "-Lu6w6_P1NA" },
        ]
    },
    {
        "type": "select",
        "limit": 3,
        "question": "Favorite Game Update",
        "subquestion": "Choose up to 3",
        "options": [
            "Facade System",
            "Reflectrials",
            "E.G.O Threadspin 5",
            "In-combat Dialogue Subtitles",
            "Additional Loadout Keywords",
            "Consecutive Luxcavations",
            "Increased Announcer Limit and Presets",
            "Cursed & Blessed E.G.O Gifts",
            "Automatic Reselection of Revived Identities in MD",
            "Window BGM and Jukebox"
        ]
    },
    {
        "type": "compare",
        "question": "How do you rank Canto IX against the other Cantos?",
        "short": "Canto Comparison",
        "items": [
            {"long": "Canto I: The Outcast", "short": "Canto I"},
            {"long": "Canto II: The Unloving", "short": "Canto II"},
            {"long": "Canto III: The Unconfronting", "short": "Canto III"},
            {"long": "Canto IV: The Unchanging", "short": "Canto IV"},
            {"long": "Canto V: The Evil Defining", "short": "Canto V"},
            {"long": "Canto VI: The Heartbreaking", "short": "Canto VI"},
            {"long": "Canto VII: The Dream Ending", "short": "Canto VII"},
            {"long": "Canto VIII: The Surrendered Witnessing", "short": "Canto VIII"}
        ]
    },
    {
        "type": "rating",
        "question": "From 0-10, how do you rate Season 7 as a whole?",
        "short": "Overall Season Rating"
    },
    {
        "type": "other",
        "question": "Anything you want to say about Season 7 or in preparation for Season 8?",
        "short": "Other comments on Season 7 or 8",
        "subquestion": "Answers will be anonymously displayed in the results",
    }
]